import java.io.OutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintWriter;
import java.util.Scanner;

/**
 * Code generated by CHelper
 */
public class Main {
    public static void main(String[] args) {
        InputStream inputStream = System.in;
        OutputStream outputStream = System.out;
        Scanner in = new Scanner(inputStream);
        PrintWriter out = new PrintWriter(outputStream);
        ASquare solver = new ASquare();
        solver.solve(1, in, out);
        out.close();
    }

    static class ASquare {
        public void solve(int testNumber, Scanner in, PrintWriter out) {
            int t = in.nextInt();
            while (t-- > 0) solveCase(in, out);
        }

        private void solveCase(Scanner in, PrintWriter out) {
            int[] a = new int[4];
            for (int i = 0; i < 4; i++) {
                a[i] = in.nextInt();
            }
            boolean yes = true;
            for (int i = 1; i < 4; i++) {
                if (a[i] != a[0]) {
                    yes = false;
                    break;
                }
            }
            out.println(yes ? "YES" : "NO");
        }

    }
}
 
