import java.io.OutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintWriter;
import java.util.HashMap;
import java.io.IOException;
import java.io.InputStream;

/**
 * Code generated by CHelper
 * Original Author: Egor Kulikov
 * Forked and Updated at: https://github.com/nathanwn/idea-chelper
 */
public class Main {
    public static void main(String[] args) {
        InputStream inputStream = System.in;
        OutputStream outputStream = System.out;
        InputReader in = new InputReader(inputStream);
        PrintWriter out = new PrintWriter(outputStream);
        CGoodSubarrays solver = new CGoodSubarrays();
        solver.solve(1, in, out);
        out.close();
    }

    static class CGoodSubarrays {
        public void solve(int testNumber, InputReader in, PrintWriter out) {
            int t = in.nextInt();
            while (t-- > 0) solveCase(in, out);
        }

        private void solveCase(InputReader in, PrintWriter out) {
            int n = in.nextInt();
            String s = in.next();
            int[] a = new int[n];
            for (int i = 0; i < n; i++) {
                a[i] = s.charAt(i) - '0';
            }
            // preSum[x] = sum(a[0..x - 1])
            // sum([l..r]) == r - l + 1
            // preSum[r + 1] - preSum[l] == r - l + 1
            // preSum[r + 1] - r == preSum[l] - l + 1 == target
            // sum([0..r]) - r == sum([0..l - 1]) - l + 1 == target
            // For every r, add the number of l satisfying the above equation.
            // cnt[target]: number of l with preSum[l] - l + 1 == target
            HashMap<Integer, Integer> cnt = new HashMap<>();
            cnt.put(1, 1);  // base case with l == 0
            int curSum = 0;  // sum(a[0..r])
            long ans = 0;
            for (int r = 0; r < n; r++) {
                curSum += a[r];
                int target = curSum - r;
                ans += cnt.getOrDefault(target, 0);

                // Construct new target from the formula f(l) = sum([0..l - 1]) - l + 1.
                // Base case for l = 0 has already been put before the first iteration.
                // Therefore, in the first iteration, we need to start with l = 1.
                // As l = 1 and r = 0 in the first iteration
                // => f(l) == f(r + 1) is an invariant thereafter.
                int newTarget = curSum - (r + 1) + 1;
                cnt.put(newTarget, cnt.getOrDefault(newTarget, 0) + 1);
            }
            out.println(ans);
        }

    }

    static class InputReader {
        private InputStream stream;
        private byte[] buf = new byte[65536];
        private int curChar;
        private int numChars;

        public InputReader(InputStream stream) {
            this.stream = stream;
        }

        public int get() {
            if (numChars == -1) {
                throw new RuntimeException();
            }
            if (curChar >= numChars) {
                curChar = 0;
                try {
                    numChars = stream.read(buf);
                } catch (IOException e) {
                    throw new RuntimeException();
                }
                if (numChars <= 0) {
                    return -1;
                }
            }
            return buf[curChar++];
        }

        public String next() {
            int c = get();
            while (isWhitespace(c)) {
                c = get();
            }
            StringBuilder res = new StringBuilder();
            do {
                if (Character.isValidCodePoint(c)) {
                    res.appendCodePoint(c);
                }
                c = get();
            } while (!isWhitespace(c));
            return res.toString();
        }

        public int nextInt() {
            int c = get();
            while (isWhitespace(c)) {
                c = get();
            }
            int sgn = 1;
            if (c == '-') {
                sgn = -1;
                c = get();
            }
            int res = 0;
            do {
                if (c < '0' || c > '9') {
                    throw new RuntimeException();
                }
                res *= 10;
                res += c - '0';
                c = get();
            } while (!isWhitespace(c));
            return res * sgn;
        }

        public static boolean isWhitespace(int c) {
            return c == ' ' || c == '\n' || c == '\r' || c == '\t' || c == -1;
        }

    }
}

