import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.util.Arrays;

/**
 * Code generated by CHelper
 * Original Author: Egor Kulikov
 * Forked and Updated at: https://github.com/nathanwn/idea-chelper
 */
public class Main {
    public static void main(String[] args) {
        InputStream inputStream = System.in;
        OutputStream outputStream = System.out;
        InputReader in = new InputReader(inputStream);
        PrintWriter out = new PrintWriter(outputStream);
        DXmasOrHysteria solver = new DXmasOrHysteria();
        solver.solve(1, in, out);
        out.close();
    }

    static class DXmasOrHysteria {
        public void solve(int testNumber, InputReader in, PrintWriter out) {
            int t = in.nextInt();
            while (t-- > 0) {
                solveCase(in, out);
            }
        }

        private void solveCase(InputReader in, PrintWriter out) {
            int n = in.nextInt();  // Total number of elves
            int m = in.nextInt();  // Number of elves alive after the process
            int k = n - m;         // Number of elves killed after the process
            DXmasOrHysteria.Elf[] a = new DXmasOrHysteria.Elf[n];
            for (int i = 0; i < n; i++) {
                a[i] = new DXmasOrHysteria.Elf(i + 1, in.nextInt());
            }

            // Observation 1: After each attach, there is always at least 1 elf killed.
            // Observation 2: The m alive elves have all attacked once - otherwise the
            //                process can still continue.

            // Prop 1: k >= m for a process with valid outcome (n, m).
            //         If k < m, then the process can still continue, and therefore
            //         the outcome (n, m) is invalid.
            // Proof: From Ob. 2, the m alive elves have all attacked once.
            //        Therefore, there are at least m elves killed, i.e. k >= m.
            if (k < m) {
                out.println(-1);
                return;
            }

            // Property 2: There is always a way to reduce a set of x elves to 1 elf -
            //             by letting the smallest alive attacking the next larger.

            // Property 3: There is always a way to reduce a set of x elves to 0 elf -
            //             if we are allowed to "borrow" 1 elf larger than all elves
            //             in the set.

            // Solution for m > 0:
            // We can eventually let the largest m elves (call this set 1) attack
            // and kill the next m elves (call this set 2).
            // For the remaining n - 2m remaining elves (call this set 3), we use
            // the method in prop. 3 to reduce them to 0 first, by "borrowing" the
            // smallest elf from set 2.
            // The number of iterations is k, with exactly 1 elf killed per iteration.
            // This method is only valid if m > 0, since with m == 0 set 2 is empty,
            // and there is no elf to borrow.

            // Solution for m == 0:
            // There is a solution if there is a set of elves being able to kill
            // the largest (call this set 1). The set of remaining elves (call this
            // set 2) can be reduced to 0 by borrowing the smallest elf from set 1.
            // Set 1 is also by definition always non-empty (the largest elf always
            // has a positive health value).
            // Note that there are only k - 1 iterations , as the last one kills 2 elves.

            // Implementation note to safely avoid having one elf attacking twice:
            // - For m > 0, always let the larger attack the smaller
            //   This is especially valid in the case where the alive elf killing another,
            //   where the alive elf must be the attacker.
            //   Otherwise, it can still attack afterward.
            // - For m == 0, always let the smaller attack the larger.
            //   This is because the largest elf needs to participate in multiple attacks.
            Arrays.sort(a, (DXmasOrHysteria.Elf x, DXmasOrHysteria.Elf y) -> -Integer.compare(x.val, y.val));
            if (m > 0) {
                out.println(k);
                for (int i = 0; i < n - 2 * m; i++) {
                    int j = n - i - 1;
                    out.println(a[j - 1].id + " " + a[j].id);
                }
                for (int i = 0; i < m; i++) {
                    out.println(a[i].id + " " + a[i + m].id);
                }
            } else {
                int last = -1;
                int sum = 0;
                for (int i = 1; i < n; i++) {
                    sum += a[i].val;
                    if (sum >= a[0].val) {
                        last = i;
                        break;
                    }
                }
                if (last == -1) {
                    out.println(-1);
                } else {
                    out.println(n - 1);
                    for (int i = n - 1; i > last; i--) {
                        out.println(a[i].id + " " + a[i - 1].id);
                    }
                    for (int i = 1; i <= last; i++) {
                        out.println(a[i].id + " " + a[0].id);
                    }
                }
            }
        }

        static class Elf {
            int id;
            int val;

            Elf(int id, int val) {
                this.id = id;
                this.val = val;
            }

        }

    }

    static class InputReader {
        private InputStream stream;
        private byte[] buf = new byte[65536];
        private int curChar;
        private int numChars;

        public InputReader(InputStream stream) {
            this.stream = stream;
        }

        public int get() {
            if (numChars == -1) {
                throw new RuntimeException();
            }
            if (curChar >= numChars) {
                curChar = 0;
                try {
                    numChars = stream.read(buf);
                } catch (IOException e) {
                    throw new RuntimeException();
                }
                if (numChars <= 0) {
                    return -1;
                }
            }
            return buf[curChar++];
        }

        public int nextInt() {
            int c = get();
            while (isWhitespace(c)) {
                c = get();
            }
            int sgn = 1;
            if (c == '-') {
                sgn = -1;
                c = get();
            }
            int res = 0;
            do {
                if (c < '0' || c > '9') {
                    throw new RuntimeException();
                }
                res *= 10;
                res += c - '0';
                c = get();
            } while (!isWhitespace(c));
            return res * sgn;
        }

        public static boolean isWhitespace(int c) {
            return c == ' ' || c == '\n' || c == '\r' || c == '\t' || c == -1;
        }

    }
}
