import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.util.Arrays;
import java.util.Comparator;

/**
 * Code generated by CHelper
 * Original Author: Egor Kulikov
 * Forked and Updated at: https://github.com/nathanwn/idea-chelper
 */
public class Main {
    public static void main(String[] args) {
        InputStream inputStream = System.in;
        OutputStream outputStream = System.out;
        InputReader in = new InputReader(inputStream);
        PrintWriter out = new PrintWriter(outputStream);
        BKefaAndCompany solver = new BKefaAndCompany();
        solver.solve(1, in, out);
        out.close();
    }

    static class BKefaAndCompany {
        public void solve(int testNumber, InputReader in, PrintWriter out) {
            int n = in.nextInt();
            int d = in.nextInt();
            BKefaAndCompany.Friend[] friends = new BKefaAndCompany.Friend[n];
            for (int i = 0; i < n; i++) {
                int money = in.nextInt();
                int friendship = in.nextInt();
                friends[i] = new BKefaAndCompany.Friend(money, friendship);
            }
            Arrays.sort(friends, Comparator.comparingInt((BKefaAndCompany.Friend f) -> f.money));
            long maxFriendshipSum = 0;
            long curFriendshipSum = 0;
            int l = 0;
            int r = 0;
            while (l < n && r < n) {
                if (friends[r].money - friends[l].money >= d) {
                    curFriendshipSum -= friends[l].friendship;
                    l++;
                    continue;
                }
                curFriendshipSum += friends[r].friendship;
                maxFriendshipSum = Math.max(maxFriendshipSum, curFriendshipSum);
                r++;
            }
            out.println(maxFriendshipSum);
        }

        static class Friend {
            int money;
            int friendship;

            public Friend(int m, int s) {
                this.money = m;
                this.friendship = s;
            }

        }

    }

    static class InputReader {
        private InputStream stream;
        private byte[] buf = new byte[65536];
        private int curChar;
        private int numChars;

        public InputReader(InputStream stream) {
            this.stream = stream;
        }

        public int get() {
            if (numChars == -1) {
                throw new RuntimeException();
            }
            if (curChar >= numChars) {
                curChar = 0;
                try {
                    numChars = stream.read(buf);
                } catch (IOException e) {
                    throw new RuntimeException();
                }
                if (numChars <= 0) {
                    return -1;
                }
            }
            return buf[curChar++];
        }

        public int nextInt() {
            int c = get();
            while (isWhitespace(c)) {
                c = get();
            }
            int sgn = 1;
            if (c == '-') {
                sgn = -1;
                c = get();
            }
            int res = 0;
            do {
                if (c < '0' || c > '9') {
                    throw new RuntimeException();
                }
                res *= 10;
                res += c - '0';
                c = get();
            } while (!isWhitespace(c));
            return res * sgn;
        }

        public static boolean isWhitespace(int c) {
            return c == ' ' || c == '\n' || c == '\r' || c == '\t' || c == -1;
        }

    }
}
