#
#Sat Dec 20 20:31:33 ICT 2025
archiveDirectory=archive/unsorted
author=
defaultDirectory=src/main/java/tasks
enableUnitTests=false
excludePackages=java.,javax.,com.sun.
extensionProposed=true
failOnIntegerOverflowForNewTasks=false
inputClass=io.github.nathanwn.io.InputReader
libraryVersion=2
outputClass=java.io.PrintWriter
outputDirectory=output
smartTesting=true
testDirectory=lib/test
