import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;

/**
 * Code generated by CHelper
 * Original Author: Egor Kulikov
 * Forked and Updated at: https://github.com/nathanwn/idea-chelper
 */
public class Main {
    public static void main(String[] args) {
        InputStream inputStream = System.in;
        OutputStream outputStream = System.out;
        InputReader in = new InputReader(inputStream);
        PrintWriter out = new PrintWriter(outputStream);
        DManyRepunitSum solver = new DManyRepunitSum();
        solver.solve(1, in, out);
        out.close();
    }

    static class DManyRepunitSum {
        static final int N = 200_000;

        public void solve(int testNumber, InputReader in, PrintWriter out) {
            int n = in.nextInt();
            int[] a = new int[n];
            for (int i = 0; i < n; i++) {
                a[i] = in.nextInt();
            }
            int[] cnt = new int[N + 1];
            for (int i = 0; i < n; i++) {
                cnt[a[i]]++;
            }
            for (int i = N - 1; i >= 1; i--) {
                cnt[i] += cnt[i + 1];
            }
            StringBuilder res = new StringBuilder();
            long carry = 0;
            for (int i = 1; i <= N; i++) {
                long sum = carry + cnt[i];
                long d = sum % 10;
                res.append(d);
                carry = sum / 10;
            }
            while (carry > 0) {
                long d = carry % 10;
                res.append(d);
                carry /= 10;
            }
            String ans = res.reverse().toString();
            int start = 0;
            for (int i = 0; i < ans.length(); i++) {
                if (ans.charAt(i) != '0') {
                    start = i;
                    break;
                }
            }
            out.println(ans.substring(start));
        }

    }

    static class InputReader {
        private InputStream stream;
        private byte[] buf = new byte[65536];
        private int curChar;
        private int numChars;

        public InputReader(InputStream stream) {
            this.stream = stream;
        }

        public int get() {
            if (numChars == -1) {
                throw new RuntimeException();
            }
            if (curChar >= numChars) {
                curChar = 0;
                try {
                    numChars = stream.read(buf);
                } catch (IOException e) {
                    throw new RuntimeException();
                }
                if (numChars <= 0) {
                    return -1;
                }
            }
            return buf[curChar++];
        }

        public int nextInt() {
            int c = get();
            while (isWhitespace(c)) {
                c = get();
            }
            int sgn = 1;
            if (c == '-') {
                sgn = -1;
                c = get();
            }
            int res = 0;
            do {
                if (c < '0' || c > '9') {
                    throw new RuntimeException();
                }
                res *= 10;
                res += c - '0';
                c = get();
            } while (!isWhitespace(c));
            return res * sgn;
        }

        public static boolean isWhitespace(int c) {
            return c == ' ' || c == '\n' || c == '\r' || c == '\t' || c == -1;
        }

    }
}

