import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;

/**
 * Code generated by CHelper
 * Original Author: Egor Kulikov
 * Forked and Updated at: https://github.com/nathanwn/idea-chelper
 */
public class Main {
    public static void main(String[] args) {
        InputStream inputStream = System.in;
        OutputStream outputStream = System.out;
        InputReader in = new InputReader(inputStream);
        PrintWriter out = new PrintWriter(outputStream);
        CWoodcutters solver = new CWoodcutters();
        solver.solve(1, in, out);
        out.close();
    }

    static class CWoodcutters {
        public void solve(int testNumber, InputReader in, PrintWriter out) {
            int n = in.nextInt();
            int[] x = new int[n];
            int[] h = new int[n];
            for (int i = 0; i < n; i++) {
                x[i] = in.nextInt();
                h[i] = in.nextInt();
            }
            // maxTrees[i + 1][a]: maximum number of trees after considering trees
            //                     in the range [0..i] and taking action a at i.
            final int LEFT = 0;
            final int KEEP = 1;
            final int RIGHT = 2;
            final int ACTIONS = 3;
            int[][] maxTrees = new int[n + 1][ACTIONS];
            int[][] rightMost = new int[n + 1][ACTIONS];
            for (int action = 0; action < ACTIONS; action++) {
                rightMost[0][action] = Integer.MIN_VALUE;
            }
            for (int i = 0; i < n; i++) {
                // LEFT
                int maxTreesIfLeft = -1;
                int rightMostIfLeft = 0;
                if (x[i] - h[i] > rightMost[i][LEFT]) {
                    int val = maxTrees[i][LEFT] + 1;
                    if (maxTreesIfLeft < val) {
                        maxTreesIfLeft = val;
                        rightMostIfLeft = x[i];
                    }
                }
                if (x[i] - h[i] > rightMost[i][KEEP]) {
                    int val = maxTrees[i][KEEP];
                    if (maxTreesIfLeft < val) {
                        maxTreesIfLeft = val;
                        rightMostIfLeft = x[i];
                    }
                }
                if (x[i] - h[i] > rightMost[i][RIGHT]) {
                    int val = maxTrees[i][RIGHT] + 1;
                    if (maxTreesIfLeft < val) {
                        maxTreesIfLeft = val;
                        rightMostIfLeft = x[i];
                    }
                }
                if (maxTreesIfLeft > -1) {
                    maxTrees[i + 1][LEFT] = maxTreesIfLeft;
                    rightMost[i + 1][LEFT] = rightMostIfLeft;
                }
                // KEEP
                int maxTreesIfKeep = -1;
                int rightMostIfKeep = 0;
                if (x[i] > rightMost[i][LEFT]) {
                    int val = maxTrees[i][LEFT] + 1;
                    if (maxTreesIfKeep < val) {
                        maxTreesIfKeep = val;
                        rightMostIfKeep = x[i];
                    }
                }
                if (x[i] > rightMost[i][KEEP]) {
                    int val = maxTrees[i][KEEP];
                    if (maxTreesIfKeep < val) {
                        maxTreesIfKeep = val;
                        rightMostIfKeep = x[i];
                    }
                }
                if (x[i] > rightMost[i][RIGHT]) {
                    int val = maxTrees[i][RIGHT] + 1;
                    if (maxTreesIfKeep < val) {
                        maxTreesIfKeep = val;
                        rightMostIfKeep = x[i];
                    }
                }
                if (maxTreesIfKeep > -1) {
                    maxTrees[i + 1][KEEP] = maxTreesIfKeep;
                    rightMost[i + 1][KEEP] = rightMostIfKeep;
                }
                // RIGHT
                int maxTreesIfRight = -1;
                int rightMostIfRight = 0;
                if (x[i] > rightMost[i][LEFT]) {
                    int val = maxTrees[i][LEFT] + 1;
                    if (maxTreesIfRight < val) {
                        maxTreesIfRight = val;
                        rightMostIfRight = x[i] + h[i];
                    }
                }
                if (x[i] > rightMost[i][KEEP]) {
                    int val = maxTrees[i][KEEP];
                    if (maxTreesIfRight < val) {
                        maxTreesIfRight = val;
                        rightMostIfRight = x[i] + h[i];
                    }
                }
                if (x[i] > rightMost[i][RIGHT]) {
                    int val = maxTrees[i][RIGHT] + 1;
                    if (maxTreesIfRight < val) {
                        maxTreesIfRight = val;
                        rightMostIfRight = x[i] + h[i];
                    }
                }
                if (maxTreesIfRight > -1) {
                    maxTrees[i + 1][RIGHT] = maxTreesIfRight;
                    rightMost[i + 1][RIGHT] = rightMostIfRight;
                }
            }

            int ans = 0;
            for (int action = 0; action < ACTIONS; action++) {
                ans = Math.max(ans, maxTrees[n][action]);
            }
            out.println(ans);
        }

    }

    static class InputReader {
        private InputStream stream;
        private byte[] buf = new byte[65536];
        private int curChar;
        private int numChars;

        public InputReader(InputStream stream) {
            this.stream = stream;
        }

        public int get() {
            if (numChars == -1) {
                throw new RuntimeException();
            }
            if (curChar >= numChars) {
                curChar = 0;
                try {
                    numChars = stream.read(buf);
                } catch (IOException e) {
                    throw new RuntimeException();
                }
                if (numChars <= 0) {
                    return -1;
                }
            }
            return buf[curChar++];
        }

        public int nextInt() {
            int c = get();
            while (isWhitespace(c)) {
                c = get();
            }
            int sgn = 1;
            if (c == '-') {
                sgn = -1;
                c = get();
            }
            int res = 0;
            do {
                if (c < '0' || c > '9') {
                    throw new RuntimeException();
                }
                res *= 10;
                res += c - '0';
                c = get();
            } while (!isWhitespace(c));
            return res * sgn;
        }

        public static boolean isWhitespace(int c) {
            return c == ' ' || c == '\n' || c == '\r' || c == '\t' || c == -1;
        }

    }
}
