import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Map;
import java.util.TreeMap;

/**
 * Code generated by CHelper
 * Original Author: Egor Kulikov
 * Forked and Updated at: https://github.com/nathanwn/idea-chelper
 */
public class Main {
    public static void main(String[] args) {
        InputStream inputStream = System.in;
        OutputStream outputStream = System.out;
        InputReader in = new InputReader(inputStream);
        PrintWriter out = new PrintWriter(outputStream);
        DKadomatsuSubsequence solver = new DKadomatsuSubsequence();
        solver.solve(1, in, out);
        out.close();
    }

    static class DKadomatsuSubsequence {
        public void solve(int testNumber, InputReader in, PrintWriter out) {
            int n = in.nextInt();
            int[] a = new int[n];
            for (int i = 0; i < n; i++) {
                a[i] = in.nextInt();
            }
            TreeMap<Integer, ArrayList<Integer>> f3 = new TreeMap<>();
            TreeMap<Integer, ArrayList<Integer>> f5 = new TreeMap<>();
            TreeMap<Integer, ArrayList<Integer>> f7 = new TreeMap<>();
            for (int i = 0; i < n; i++) {
                if (a[i] % 3 == 0) {
                    int x = a[i] / 3;
                    if (!f3.containsKey(x)) {
                        f3.put(x, new ArrayList<>());
                    }
                    f3.get(x).add(i);
                }
                if (a[i] % 5 == 0) {
                    int x = a[i] / 5;
                    if (!f5.containsKey(x)) {
                        f5.put(x, new ArrayList<>());
                    }
                    f5.get(x).add(i);
                }
                if (a[i] % 7 == 0) {
                    int x = a[i] / 7;
                    if (!f7.containsKey(x)) {
                        f7.put(x, new ArrayList<>());
                    }
                    f7.get(x).add(i);
                }
            }
            long ans = 0;
            for (int d : f3.keySet()) {
                ArrayList<Integer> p3 = f3.get(d);
                ArrayList<Integer> p5 = f5.getOrDefault(d, null);
                if (p5 == null) continue;
                ArrayList<Integer> p7 = f7.getOrDefault(d, null);
                if (p7 == null) continue;
                ans += countTriplets(n, p3, p7, p5);
                ans += countTriplets(n, p7, p3, p5);
                ans += countTriplets(n, p5, p3, p7);
                ans += countTriplets(n, p5, p7, p3);
            }
            out.println(ans);
        }

        private long countTriplets(int n, ArrayList<Integer> px, ArrayList<Integer> py, ArrayList<Integer> pz) {
            long res = 0;
            for (int p : py) {
                int left = 0;
                if (p > 0) {
                    left = countBefore(px, p);
                }
                int right = 0;
                if (p < n - 1) {
                    right = countAfter(pz, p);
                }
                res += (long) left * right;
            }
            return res;
        }

        private int countBefore(ArrayList<Integer> a, int x) {
            int left = 0;
            int right = a.size() - 1;
            int pos = -1;
            while (left <= right) {
                int mid = left + (right - left) / 2;
                if (a.get(mid) < x) {
                    pos = mid;
                    left = mid + 1;
                } else {
                    right = mid - 1;
                }
            }
            if (pos == -1) return 0;
            return pos + 1;
        }

        private int countAfter(ArrayList<Integer> a, int x) {
            int left = 0;
            int right = a.size() - 1;
            int pos = -1;
            while (left <= right) {
                int mid = left + (right - left) / 2;
                if (a.get(mid) > x) {
                    pos = mid;
                    right = mid - 1;
                } else {
                    left = mid + 1;
                }
            }
            if (pos == -1) return 0;
            return a.size() - pos;
        }

    }

    static class InputReader {
        private InputStream stream;
        private byte[] buf = new byte[65536];
        private int curChar;
        private int numChars;

        public InputReader(InputStream stream) {
            this.stream = stream;
        }

        public int get() {
            if (numChars == -1) {
                throw new RuntimeException();
            }
            if (curChar >= numChars) {
                curChar = 0;
                try {
                    numChars = stream.read(buf);
                } catch (IOException e) {
                    throw new RuntimeException();
                }
                if (numChars <= 0) {
                    return -1;
                }
            }
            return buf[curChar++];
        }

        public int nextInt() {
            int c = get();
            while (isWhitespace(c)) {
                c = get();
            }
            int sgn = 1;
            if (c == '-') {
                sgn = -1;
                c = get();
            }
            int res = 0;
            do {
                if (c < '0' || c > '9') {
                    throw new RuntimeException();
                }
                res *= 10;
                res += c - '0';
                c = get();
            } while (!isWhitespace(c));
            return res * sgn;
        }

        public static boolean isWhitespace(int c) {
            return c == ' ' || c == '\n' || c == '\r' || c == '\t' || c == -1;
        }

    }
}
