import java.io.OutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintWriter;
import java.util.Arrays;
import java.util.Random;
import java.io.IOException;
import java.io.InputStream;

/**
 * Code generated by CHelper
 * Original Author: Egor Kulikov
 * Forked and Updated at: https://github.com/nathanwn/idea-chelper
 */
public class Main {
    public static void main(String[] args) {
        InputStream inputStream = System.in;
        OutputStream outputStream = System.out;
        InputReader in = new InputReader(inputStream);
        PrintWriter out = new PrintWriter(outputStream);
        CLittleGirlAndMaximumSum solver = new CLittleGirlAndMaximumSum();
        solver.solve(1, in, out);
        out.close();
    }

    static class CLittleGirlAndMaximumSum {
        static Random random = new Random();

        public void solve(int testNumber, InputReader in, PrintWriter out) {
            int n = in.nextInt();
            int q = in.nextInt();
            int[] a = new int[n];
            for (int i = 0; i < n; i++) {
                a[i] = in.nextInt();
            }
            CLittleGirlAndMaximumSum.LazyIntervalTree t = new CLittleGirlAndMaximumSum.LazyIntervalTree(n, 0);
            for (int j = 0; j < q; j++) {
                int l = in.nextInt() - 1;
                int r = in.nextInt() - 1;
                t.update(l, r, 1);
            }
            int[] c = new int[n];
            for (int i = 0; i < n; i++) {
                c[i] = (int) t.query(i, i);
            }
            ArrayUtil.sort(a, random);
            ArrayUtil.sort(c, random);
            long ans = 0;
            for (int i = 0; i < n; i++) {
                ans += (long) a[i] * c[i];
            }
            out.println(ans);
        }

        static class LazyIntervalTree extends AbstractLazyIntervalTree {
            public LazyIntervalTree(int len, long defaultValue) {
                super(len, defaultValue);
            }

            public long merge(long leftVal, long rightVal) {
                return leftVal + rightVal;
            }

            public void updateNode(int node, long val) {
                t[node] += val;
                z[node] += val;
            }

        }

    }

    static abstract class AbstractLazyIntervalTree {
        int n;
        public long[] t;
        public long[] z;
        boolean[] lazy;
        long defaultValue;

        public abstract long merge(long leftVal, long rightVal);

        public abstract void updateNode(int node, long val);

        void pushDown(int node) {
            if (lazy[node]) {
                updateNode(left(node), z[node]);
                updateNode(right(node), z[node]);
                z[node] = defaultValue;
                lazy[node] = false;
                lazy[left(node)] = true;
                lazy[right(node)] = true;
            }
        }

        public AbstractLazyIntervalTree(int[] a, long defaultValue) {
            this(a.length, defaultValue);
            build(a);
        }

        public AbstractLazyIntervalTree(int len, long defaultValue) {
            this.defaultValue = defaultValue;
            n = 1;
            while (n < len) n <<= 1;
            t = new long[2 * n];
            z = new long[2 * n];
            lazy = new boolean[2 * n];
            if (defaultValue != 0) {
                Arrays.fill(t, defaultValue);
            }
        }

        int left(int node) {
            return node << 1;
        }

        int right(int node) {
            return (node << 1) + 1;
        }

        void build(int[] a) {
            for (int i = 0; i < a.length; i++) {
                t[n + i] = a[i];
            }
            for (int i = n - 1; i > 0; i--) {
                t[i] = merge(t[left(i)], t[right(i)]);
            }
        }

        long query(int from, int to, int node, int nodeFrom, int nodeTo) {
            if (from <= nodeFrom && nodeTo <= to) {
                return t[node];
            }
            if (to < nodeFrom || nodeTo < from) {
                return defaultValue;
            }
            pushDown(node);
            int mid = nodeFrom + ((nodeTo - nodeFrom) >> 1);
            long leftVal = query(from, to, left(node), nodeFrom, mid);
            long rightVal = query(from, to, right(node), mid + 1, nodeTo);
            return merge(leftVal, rightVal);
        }

        public long query(int from, int to) {
            return query(from, to, 1, 0, n - 1);
        }

        void update(int from, int to, int val, int node, int nodeFrom, int nodeTo) {
            if (from <= nodeFrom && nodeTo <= to) {
                updateNode(node, val);
                lazy[node] = true;
                return;
            }
            if (to < nodeFrom || nodeTo < from) {
                return;
            }
            pushDown(node);
            int mid = nodeFrom + ((nodeTo - nodeFrom) >> 1);
            update(from, to, val, left(node), nodeFrom, mid);
            update(from, to, val, right(node), mid + 1, nodeTo);
            t[node] = merge(t[left(node)], t[right(node)]);
        }

        public void update(int from, int to, int val) {
            update(from, to, val, 1, 0, n - 1);
        }

    }

    static class ArrayUtil {
        public static void sort(int[] a, Random random) {
            shuffle(a, random);
            Arrays.sort(a);
        }

        static void shuffle(int[] a, Random random) {
            // Fisher-Yates shuffle
            for (int i = a.length - 1; i > 0; i--) {
                int j = random.nextInt(i + 1);
                int tmp = a[i];
                a[i] = a[j];
                a[j] = tmp;
            }
        }

    }

    static class InputReader {
        private InputStream stream;
        private byte[] buf = new byte[65536];
        private int curChar;
        private int numChars;

        public InputReader(InputStream stream) {
            this.stream = stream;
        }

        public int get() {
            if (numChars == -1) {
                throw new RuntimeException();
            }
            if (curChar >= numChars) {
                curChar = 0;
                try {
                    numChars = stream.read(buf);
                } catch (IOException e) {
                    throw new RuntimeException();
                }
                if (numChars <= 0) {
                    return -1;
                }
            }
            return buf[curChar++];
        }

        public int nextInt() {
            int c = get();
            while (isWhitespace(c)) {
                c = get();
            }
            int sgn = 1;
            if (c == '-') {
                sgn = -1;
                c = get();
            }
            int res = 0;
            do {
                if (c < '0' || c > '9') {
                    throw new RuntimeException();
                }
                res *= 10;
                res += c - '0';
                c = get();
            } while (!isWhitespace(c));
            return res * sgn;
        }

        public static boolean isWhitespace(int c) {
            return c == ' ' || c == '\n' || c == '\r' || c == '\t' || c == -1;
        }

    }
}
 
