import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.util.ArrayList;

/**
 * Code generated by CHelper
 * Original Author: Egor Kulikov
 * Forked and Updated at: https://github.com/nathanwn/idea-chelper
 */
public class Main {
    public static void main(String[] args) {
        InputStream inputStream = System.in;
        OutputStream outputStream = System.out;
        InputReader in = new InputReader(inputStream);
        PrintWriter out = new PrintWriter(outputStream);
        CNumberOfWays solver = new CNumberOfWays();
        solver.solve(1, in, out);
        out.close();
    }

    static class CNumberOfWays {
        public void solve(int testNumber, InputReader in, PrintWriter out) {
            int n = in.nextInt();
            int[] a = new int[n];
            for (int i = 0; i < n; i++) {
                a[i] = in.nextInt();
            }
            // preSum[i + 1] == sum(a[0..i])
            long[] preSum = new long[n + 1];
            // sufSum[i] == sum(a[i..n - 1])
            long[] sufSum = new long[n + 1];
            for (int i = 0; i < n; i++) {
                preSum[i + 1] = preSum[i] + a[i];
            }
            for (int i = n - 1; i > -1; i--) {
                sufSum[i] = sufSum[i + 1] + a[i];
            }
            long sum = preSum[n];
            if (sum % 3 != 0) {
                out.println(0);
                return;
            }
            long target = sum / 3;
            ArrayList<Integer> prefixes = new ArrayList<>();
            ArrayList<Integer> suffixes = new ArrayList<>();
            for (int i = 0; i < n; i++) {
                if (preSum[i + 1] == target) {
                    prefixes.add(i);
                }

            }
            for (int i = n - 1; i > -1; i--) {
                if (sufSum[i] == target) {
                    suffixes.add(i);
                }
            }
            long ans = 0;
            for (int pre : prefixes) {
                // Find the smallest position suf larger than (pre + 1) in suffixes.
                // The +1 is to ensure the middle segment is non-empty
                int left = 0;
                int right = suffixes.size() - 1;
                int sufId = -1;
                while (left <= right) {
                    int mid = left + (right - left) / 2;
                    int suf = suffixes.get(mid);
                    if (suf > pre + 1) {
                        sufId = mid;
                        left = mid + 1;
                    } else {
                        right = mid - 1;
                    }
                }
                if (sufId != -1) {
                    ans += sufId + 1;
                }
            }
            out.println(ans);
        }

    }

    static class InputReader {
        private InputStream stream;
        private byte[] buf = new byte[65536];
        private int curChar;
        private int numChars;

        public InputReader(InputStream stream) {
            this.stream = stream;
        }

        public int get() {
            if (numChars == -1) {
                throw new RuntimeException();
            }
            if (curChar >= numChars) {
                curChar = 0;
                try {
                    numChars = stream.read(buf);
                } catch (IOException e) {
                    throw new RuntimeException();
                }
                if (numChars <= 0) {
                    return -1;
                }
            }
            return buf[curChar++];
        }

        public int nextInt() {
            int c = get();
            while (isWhitespace(c)) {
                c = get();
            }
            int sgn = 1;
            if (c == '-') {
                sgn = -1;
                c = get();
            }
            int res = 0;
            do {
                if (c < '0' || c > '9') {
                    throw new RuntimeException();
                }
                res *= 10;
                res += c - '0';
                c = get();
            } while (!isWhitespace(c));
            return res * sgn;
        }

        public static boolean isWhitespace(int c) {
            return c == ' ' || c == '\n' || c == '\r' || c == '\t' || c == -1;
        }

    }
}
