import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Random;

/**
 * Code generated by CHelper
 * Original Author: Egor Kulikov
 * Forked and Updated at: https://github.com/nathanwn/idea-chelper
 */
public class Main {
    public static void main(String[] args) {
        InputStream inputStream = System.in;
        OutputStream outputStream = System.out;
        InputReader in = new InputReader(inputStream);
        PrintWriter out = new PrintWriter(outputStream);
        DForbiddenList2 solver = new DForbiddenList2();
        solver.solve(1, in, out);
        out.close();
    }

    static class DForbiddenList2 {
        static Random random = new Random();

        public void solve(int testNumber, InputReader in, PrintWriter out) {
            int n = in.nextInt();
            int q = in.nextInt();
            int[] a = new int[n];
            for (int i = 0; i < n; i++) {
                a[i] = in.nextInt();
            }
            int[][] b = new int[q][2];
            for (int j = 0; j < q; j++) {
                b[j][0] = in.nextInt();
                b[j][1] = in.nextInt();
            }
            ArrayUtil.sort(a, random);
            ArrayList<DForbiddenList2.Gap> gaps = new ArrayList<>(n);
            gaps.add(new DForbiddenList2.Gap(0, a[0]));
            for (int i = 1; i < n; i++) {
                int len = a[i] - a[i - 1] - 1;
                if (len == 0) continue;
                gaps.add(new DForbiddenList2.Gap(a[i - 1] + 1, len));
            }
            gaps.add(new DForbiddenList2.Gap(a[n - 1] + 1, (int) 1e9 * 2));
            int m = gaps.size();
            long[] p = new long[m + 1];
            for (int k = 0; k < m; k++) {
                p[k + 1] = p[k] + gaps.get(k).len;
            }
            for (int j = 0; j < q; j++) {
                int x = b[j][0];
                int y = b[j][1];
                int ans = solve(gaps, p, m, x, y);
                out.println(ans);
            }
        }

        private int solve(ArrayList<DForbiddenList2.Gap> gaps, long[] p, int m, int x, int y) {
            int gid1 = findUpperBoundGap(gaps, x);  // [1, m]
            if (gid1 == 0) throw new AssertionError();
            if (gid1 == m) {
                return x + y - 1;
            }
            if (x > gaps.get(gid1 - 1).last()) {
                gid1++;
                x = gaps.get(gid1 - 1).start;
            }
            int gapLast = gaps.get(gid1 - 1).last();
            if (gapLast - x + 1 >= y) {
                return x + y - 1;
            }
            y -= gapLast - x + 1;
            // Find first gap id gid2 with sum([gid1 + 1, gid2]) >= y
            int lo = gid1;
            int hi = m - 1;
            int gid2 = -1;
            while (lo <= hi) {
                int mid = lo + (hi - lo) / 2;
                long s = p[mid + 1] - p[gid1];
                if (s >= y) {
                    gid2 = mid;
                    hi = mid - 1;
                } else {
                    lo = mid + 1;
                }
            }
            if (gid2 == -1) throw new AssertionError();
            y -= (int) (p[gid2] - p[gid1]);
            return gaps.get(gid2).start + y - 1;
        }

        private int findUpperBoundGap(ArrayList<DForbiddenList2.Gap> gaps, int x) {
            int m = gaps.size();
            int lo = 0;
            int hi = m - 1;
            int gapId = m;
            while (lo <= hi) {
                int mid = lo + (hi - lo) / 2;
                if (gaps.get(mid).start > x) {
                    gapId = mid;
                    hi = mid - 1;
                } else {
                    lo = mid + 1;
                }
            }
            return gapId;
        }

        static class Gap {
            int start;
            int len;

            public Gap(int start, int len) {
                this.start = start;
                this.len = len;
            }

            int last() {
                return start + len - 1;
            }

        }

    }

    static class InputReader {
        private InputStream stream;
        private byte[] buf = new byte[65536];
        private int curChar;
        private int numChars;

        public InputReader(InputStream stream) {
            this.stream = stream;
        }

        public int get() {
            if (numChars == -1) {
                throw new RuntimeException();
            }
            if (curChar >= numChars) {
                curChar = 0;
                try {
                    numChars = stream.read(buf);
                } catch (IOException e) {
                    throw new RuntimeException();
                }
                if (numChars <= 0) {
                    return -1;
                }
            }
            return buf[curChar++];
        }

        public int nextInt() {
            int c = get();
            while (isWhitespace(c)) {
                c = get();
            }
            int sgn = 1;
            if (c == '-') {
                sgn = -1;
                c = get();
            }
            int res = 0;
            do {
                if (c < '0' || c > '9') {
                    throw new RuntimeException();
                }
                res *= 10;
                res += c - '0';
                c = get();
            } while (!isWhitespace(c));
            return res * sgn;
        }

        public static boolean isWhitespace(int c) {
            return c == ' ' || c == '\n' || c == '\r' || c == '\t' || c == -1;
        }

    }

    static class ArrayUtil {
        public static void sort(int[] a, Random random) {
            shuffle(a, random);
            Arrays.sort(a);
        }

        static void shuffle(int[] a, Random random) {
            // Fisher-Yates shuffle
            for (int i = a.length - 1; i > 0; i--) {
                int j = random.nextInt(i + 1);
                int tmp = a[i];
                a[i] = a[j];
                a[j] = tmp;
            }
        }

    }
}
