import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;

/**
 * Code generated by CHelper
 * Original Author: Egor Kulikov
 * Forked and Updated at: https://github.com/nathanwn/idea-chelper
 */
public class Main {
    public static void main(String[] args) {
        InputStream inputStream = System.in;
        OutputStream outputStream = System.out;
        InputReader in = new InputReader(inputStream);
        PrintWriter out = new PrintWriter(outputStream);
        CHamburgers solver = new CHamburgers();
        solver.solve(1, in, out);
        out.close();
    }

    static class CHamburgers {
        final int T = 3;
        final long MAX = (long) 1e12 + 100;

        public void solve(int testNumber, InputReader in, PrintWriter out) {
            int[] recipe = parseRecipe(in.next());
            int[] already = new int[T];
            for (int i = 0; i < T; i++) {
                already[i] = in.nextInt();
            }
            int[] price = new int[T];
            for (int i = 0; i < T; i++) {
                price[i] = in.nextInt();
            }
            long budget = in.nextLong();

            // binary search max number of burgers
            long ans = 0;
            long min = 0;
            long max = MAX;
            while (min <= max) {
                long mid = min + (max - min) / 2;
                if (canMake(mid, recipe, already, price, budget)) {
                    ans = mid;
                    min = mid + 1;
                } else {
                    max = mid - 1;
                }
            }
            out.println(ans);
        }

        private boolean canMake(long num, int[] recipe, int[] already, int[] price, long budget) {
            long[] total = new long[T];
            for (int i = 0; i < T; i++) {
                total[i] = num * recipe[i];
            }
            long[] need = new long[T];
            for (int i = 0; i < T; i++) {
                need[i] = Math.max(0, total[i] - already[i]);
            }
            long cost = 0;
            for (int i = 0; i < T; i++) {
                cost += need[i] * price[i];
            }
            return cost <= budget;
        }

        int[] parseRecipe(String input) {
            int[] recipe = new int[T];
            for (int i = 0; i < input.length(); i++) {
                char c = input.charAt(i);
                if (c == 'B') {
                    recipe[0]++;
                } else if (c == 'S') {
                    recipe[1]++;
                } else {
                    recipe[2]++;
                }
            }
            return recipe;
        }

    }

    static class InputReader {
        private InputStream stream;
        private byte[] buf = new byte[65536];
        private int curChar;
        private int numChars;

        public InputReader(InputStream stream) {
            this.stream = stream;
        }

        public int get() {
            if (numChars == -1) {
                throw new RuntimeException();
            }
            if (curChar >= numChars) {
                curChar = 0;
                try {
                    numChars = stream.read(buf);
                } catch (IOException e) {
                    throw new RuntimeException();
                }
                if (numChars <= 0) {
                    return -1;
                }
            }
            return buf[curChar++];
        }

        public String next() {
            int c = get();
            while (isWhitespace(c)) {
                c = get();
            }
            StringBuilder res = new StringBuilder();
            do {
                if (Character.isValidCodePoint(c)) {
                    res.appendCodePoint(c);
                }
                c = get();
            } while (!isWhitespace(c));
            return res.toString();
        }

        public int nextInt() {
            int c = get();
            while (isWhitespace(c)) {
                c = get();
            }
            int sgn = 1;
            if (c == '-') {
                sgn = -1;
                c = get();
            }
            int res = 0;
            do {
                if (c < '0' || c > '9') {
                    throw new RuntimeException();
                }
                res *= 10;
                res += c - '0';
                c = get();
            } while (!isWhitespace(c));
            return res * sgn;
        }

        public long nextLong() {
            int c = get();
            while (isWhitespace(c)) {
                c = get();
            }
            int sgn = 1;
            if (c == '-') {
                sgn = -1;
                c = get();
            }
            long res = 0;
            do {
                if (c < '0' || c > '9') {
                    throw new RuntimeException();
                }
                res *= 10;
                res += c - '0';
                c = get();
            } while (!isWhitespace(c));
            return res * sgn;
        }

        public static boolean isWhitespace(int c) {
            return c == ' ' || c == '\n' || c == '\r' || c == '\t' || c == -1;
        }

    }
}
