import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;

/**
 * Code generated by CHelper
 * Original Author: Egor Kulikov
 * Forked and Updated at: https://github.com/nathanwn/idea-chelper
 */
public class Main {
    public static void main(String[] args) {
        InputStream inputStream = System.in;
        OutputStream outputStream = System.out;
        InputReader in = new InputReader(inputStream);
        PrintWriter out = new PrintWriter(outputStream);
        CDivisibilityByEight solver = new CDivisibilityByEight();
        solver.solve(1, in, out);
        out.close();
    }

    static class CDivisibilityByEight {
        public void solve(int testNumber, InputReader in, PrintWriter out) {
            String s = in.next();
            int n = s.length();
            int[] digits = new int[n];
            for (int i = 0; i < n; i++) {
                digits[i] = s.charAt(i) - '0';
            }
            final int D = 8;
            // dp[i + 1][r]: whether using the prefix digits[0..i] we can create
            //               a number mod 8 = r
            boolean[][] dp = new boolean[n + 1][D];
            // prev[i][r]: state where state[0] is previous r, state[1] is the digit
            int[][][] prev = new int[n + 1][D][];
            for (int i = 0; i < n; i++) {
                int digit = digits[i];
                // digits[i] starts a new number
                dp[i + 1][digit % 8] = true;
                prev[i + 1][digit % 8] = new int[]{-1, digit};
                // do not append digits[i] to any number
                for (int r = 0; r < 8; r++) {
                    if (dp[i][r]) {
                        dp[i + 1][r] = true;
                        prev[i + 1][r] = new int[]{r, -1};
                    }
                }
                // append digits[i] to some number
                for (int r = 0; r < 8; r++) {
                    if (dp[i][r]) {
                        int nr = r * 10;
                        nr += digit;
                        nr %= 8;
                        dp[i + 1][nr] = true;
                        prev[i + 1][nr] = new int[]{r, digit};
                    }
                }
            }
            if (!dp[n][0]) {
                out.println("NO");
                return;
            }
            out.println("YES");
            StringBuilder sb = new StringBuilder();
            {
                int r = 0;
                int j = n;
                while (true) {
                    int digit = prev[j][r][1];
                    if (digit != -1) {
                        sb.append(digit);
                    }
                    r = prev[j][r][0];
                    if (r == -1) break;
                    j--;
                }
            }
            sb.reverse();
            out.println(sb);
        }

    }

    static class InputReader {
        private InputStream stream;
        private byte[] buf = new byte[65536];
        private int curChar;
        private int numChars;

        public InputReader(InputStream stream) {
            this.stream = stream;
        }

        public int get() {
            if (numChars == -1) {
                throw new RuntimeException();
            }
            if (curChar >= numChars) {
                curChar = 0;
                try {
                    numChars = stream.read(buf);
                } catch (IOException e) {
                    throw new RuntimeException();
                }
                if (numChars <= 0) {
                    return -1;
                }
            }
            return buf[curChar++];
        }

        public String next() {
            int c = get();
            while (isWhitespace(c)) {
                c = get();
            }
            StringBuilder res = new StringBuilder();
            do {
                if (Character.isValidCodePoint(c)) {
                    res.appendCodePoint(c);
                }
                c = get();
            } while (!isWhitespace(c));
            return res.toString();
        }

        public static boolean isWhitespace(int c) {
            return c == ' ' || c == '\n' || c == '\r' || c == '\t' || c == -1;
        }

    }
}
