import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;

/**
 * Code generated by CHelper
 * Original Author: Egor Kulikov
 * Forked and Updated at: https://github.com/nathanwn/idea-chelper
 */
public class Main {
    public static void main(String[] args) {
        InputStream inputStream = System.in;
        OutputStream outputStream = System.out;
        InputReader in = new InputReader(inputStream);
        PrintWriter out = new PrintWriter(outputStream);
        EABSubstring solver = new EABSubstring();
        solver.solve(1, in, out);
        out.close();
    }

    static class EABSubstring {
        public void solve(int testNumber, InputReader in, PrintWriter out) {
            int n = in.nextInt();
            String s = in.next();
            int[] a = new int[n];
            for (int i = 0; i < n; i++) {
                char c = s.charAt(i);
                if (c == 'A') {
                    a[i] = 1;
                } else if (c == 'B') {
                    a[i] = -1;
                } else {
                    a[i] = 0;
                }
            }
            // Count the number of prefixes with a specific sum. Since the
            // sum is in the range [-n, n], offset the Fenwick tree with +n.
            FenwickTree ft = new FenwickTree(2 * n + 1);
            ft.add(n, 1);  // empty segment with sum = 0
            int rightSum = 0;
            long ans = 0;
            for (int r = 0; r < n; r++) {
                rightSum += a[r];
                // Count number of leftSum < sum
                long countLeftSum = ft.sum(n + rightSum - 1);
                ans += countLeftSum;
                ft.add(n + rightSum, 1);
            }
            out.println(ans);
        }
    }

    static class FenwickTree {
        int n;
        long[] t;

        public FenwickTree(int n) {
            this.n = n;
            t = new long[n];
        }

        public FenwickTree(int[] a) {
            n = a.length;
            t = new long[n];
            for (int i = 0; i < n; i++) {
                add(i, a[i]);
            }
        }

        public void add(int i, int d) {
            for (int j = i; j < n; j = j | (j + 1)) {
                t[j] += d;
            }
        }

        public long sum(int i) {
            long res = 0;
            for (int j = i; j >= 0; j = (j & (j + 1)) - 1) {
                res += t[j];
            }
            return res;
        }
    }

    static class InputReader {
        private InputStream stream;
        private byte[] buf = new byte[65536];
        private int curChar;
        private int numChars;

        public InputReader(InputStream stream) {
            this.stream = stream;
        }

        public int get() {
            if (numChars == -1) {
                throw new RuntimeException();
            }
            if (curChar >= numChars) {
                curChar = 0;
                try {
                    numChars = stream.read(buf);
                } catch (IOException e) {
                    throw new RuntimeException();
                }
                if (numChars <= 0) {
                    return -1;
                }
            }
            return buf[curChar++];
        }

        public String next() {
            int c = get();
            while (isWhitespace(c)) {
                c = get();
            }
            StringBuilder res = new StringBuilder();
            do {
                if (Character.isValidCodePoint(c)) {
                    res.appendCodePoint(c);
                }
                c = get();
            } while (!isWhitespace(c));
            return res.toString();
        }

        public int nextInt() {
            int c = get();
            while (isWhitespace(c)) {
                c = get();
            }
            int sgn = 1;
            if (c == '-') {
                sgn = -1;
                c = get();
            }
            int res = 0;
            do {
                if (c < '0' || c > '9') {
                    throw new RuntimeException();
                }
                res *= 10;
                res += c - '0';
                c = get();
            } while (!isWhitespace(c));
            return res * sgn;
        }

        public static boolean isWhitespace(int c) {
            return c == ' ' || c == '\n' || c == '\r' || c == '\t' || c == -1;
        }

    }
}
