import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;

/**
 * Code generated by CHelper
 * Original Author: Egor Kulikov
 * Forked and Updated at: https://github.com/nathanwn/idea-chelper
 */
public class Main {
    public static void main(String[] args) {
        InputStream inputStream = System.in;
        OutputStream outputStream = System.out;
        InputReader in = new InputReader(inputStream);
        PrintWriter out = new PrintWriter(outputStream);
        CWarStrategy solver = new CWarStrategy();
        solver.solve(1, in, out);
        out.close();
    }

    static class CWarStrategy {
        public void solve(int testNumber, InputReader in, PrintWriter out) {
            int t = in.nextInt();
            while (t-- > 0) {
                solveCase(in, out);
            }
        }

        private void solveCase(InputReader in, PrintWriter out) {
            int n = in.nextInt();
            int days = in.nextInt();
            int base = in.nextInt() - 1;
            int nLeft = base;
            int nRight = n - base - 1;
            int nFirst = Math.max(nLeft, nRight);
            int nSecond = Math.min(nLeft, nRight);
            // Key observation: This is a 2-step process.
            // - Step 1: Go to the "longer" side. This takes 2f - 1 days.
            //   - Step 1a: f - 1 days for waiting to accumulate f soldiers.
            //   - Step 1b: f days for distributing the f soldiers.
            // - Step 2: Go to the "shorter" side, with f soldiers accumulated
            //           during step 1a. This takes s days, where s <= f.
            // Constraint: 2f + s - 1 <= days
            int ans = 0;
            for (int s = 0; s <= nSecond; s++) {
                int f = (days - s + 1) / 2;
                if (s > f) continue;
                int res = f + s + 1;
                if (res > ans) {
                    ans = res;
                }
            }
            ans = Math.min(ans, n);
            out.println(ans);
        }

    }

    static class InputReader {
        private InputStream stream;
        private byte[] buf = new byte[65536];
        private int curChar;
        private int numChars;

        public InputReader(InputStream stream) {
            this.stream = stream;
        }

        public int get() {
            if (numChars == -1) {
                throw new RuntimeException();
            }
            if (curChar >= numChars) {
                curChar = 0;
                try {
                    numChars = stream.read(buf);
                } catch (IOException e) {
                    throw new RuntimeException();
                }
                if (numChars <= 0) {
                    return -1;
                }
            }
            return buf[curChar++];
        }

        public int nextInt() {
            int c = get();
            while (isWhitespace(c)) {
                c = get();
            }
            int sgn = 1;
            if (c == '-') {
                sgn = -1;
                c = get();
            }
            int res = 0;
            do {
                if (c < '0' || c > '9') {
                    throw new RuntimeException();
                }
                res *= 10;
                res += c - '0';
                c = get();
            } while (!isWhitespace(c));
            return res * sgn;
        }

        public static boolean isWhitespace(int c) {
            return c == ' ' || c == '\n' || c == '\r' || c == '\t' || c == -1;
        }

    }
}
