import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;

/**
 * Code generated by CHelper
 * Original Author: Egor Kulikov
 * Forked and Updated at: https://github.com/nathanwn/idea-chelper
 */
public class Main {
    public static void main(String[] args) {
        InputStream inputStream = System.in;
        OutputStream outputStream = System.out;
        InputReader in = new InputReader(inputStream);
        PrintWriter out = new PrintWriter(outputStream);
        BAGAGAXOOORRR solver = new BAGAGAXOOORRR();
        solver.solve(1, in, out);
        out.close();
    }

    static class BAGAGAXOOORRR {
        public void solveCase(InputReader in, PrintWriter out) {
            // Note that problem asks to replace pairs of "adjacent" elements.
            // Can easily prove that we only need to check if array can be reduced
            // down to either 2 or 3 equal elements.
            // - If the array can be reduced down to an even number of equal elements,
            // it can be further reduced down to 2 equal elements.
            // - If the array can be reduced down to an odd number of equal elements,
            // it can be further reduced down to 3 equal elements.

            // Case 1: The array can be reduced down to 2 equal elements.
            // To check for this case, we just need to check if the xor of the whole
            // array is 0. Note the property: if x ^ y = 0, then x = y. This mean

            // Case 2: The array can be reduced down to 3 equal elements.
            // Iterate through all the ways to divide the array into 3 parts.
            // This solution is O(n^2).

            // We can further prove the following property for case 2:
            // If we can divide the array into odd number of parts where the xor of
            // each part is equal to a value `xorAll`, then the xor of each part is
            // also equal to `xorAll`.
            // Therefore, we just need to check if there are 3 parts
            // of the array with xor equals `xorAll`.
            // This solution is O(n).

            // Important: Be careful with 0s. Using prefix xor is messy.

            int n = in.nextInt();
            int[] a = new int[n];
            for (int i = 0; i < n; i++) {
                a[i] = in.nextInt();
            }
            int xorAll = 0;
            // Case 1
            for (int i = 0; i < n; i++) {
                xorAll ^= a[i];
            }
            if (xorAll == 0) {
                out.println("YES");
                return;
            }
            // Case 2
            int xor = 0;
            int cnt = 0;
            for (int i = 0; i < n; i++) {
                xor ^= a[i];
                if (xorAll == xor) {
                    cnt++;
                    xor = 0;
                }
            }
            out.println(cnt >= 3 ? "YES" : "NO");
        }

        public void solve(int testNumber, InputReader in, PrintWriter out) {
            int t = in.nextInt();
            while (t-- > 0) {
                solveCase(in, out);
            }
        }

    }

    static class InputReader {
        private InputStream stream;
        private byte[] buf = new byte[65536];
        private int curChar;
        private int numChars;

        public InputReader(InputStream stream) {
            this.stream = stream;
        }

        public int get() {
            if (numChars == -1) {
                throw new RuntimeException();
            }
            if (curChar >= numChars) {
                curChar = 0;
                try {
                    numChars = stream.read(buf);
                } catch (IOException e) {
                    throw new RuntimeException();
                }
                if (numChars <= 0) {
                    return -1;
                }
            }
            return buf[curChar++];
        }

        public int nextInt() {
            int c = get();
            while (isWhitespace(c)) {
                c = get();
            }
            int sgn = 1;
            if (c == '-') {
                sgn = -1;
                c = get();
            }
            int res = 0;
            do {
                if (c < '0' || c > '9') {
                    throw new RuntimeException();
                }
                res *= 10;
                res += c - '0';
                c = get();
            } while (!isWhitespace(c));
            return res * sgn;
        }

        public static boolean isWhitespace(int c) {
            return c == ' ' || c == '\n' || c == '\r' || c == '\t' || c == -1;
        }

    }
}

