import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.HashMap;

/**
 * Code generated by CHelper
 * Original Author: Egor Kulikov
 * Forked and Updated at: https://github.com/nathanwn/idea-chelper
 */
public class Main {
    public static void main(String[] args) {
        InputStream inputStream = System.in;
        OutputStream outputStream = System.out;
        InputReader in = new InputReader(inputStream);
        PrintWriter out = new PrintWriter(outputStream);
        AWinner solver = new AWinner();
        solver.solve(1, in, out);
        out.close();
    }

    static class AWinner {
        public void solve(int testNumber, InputReader in, PrintWriter out) {
            int n = in.nextInt();
            ArrayList<AWinner.Turn> turns = new ArrayList<>(n);
            for (int i = 0; i < n; i++) {
                String name = in.next();
                int score = in.nextInt();
                turns.add(new AWinner.Turn(name, score, i));
            }
            HashMap<String, Integer> scoreByName = new HashMap<>();
            for (int i = 0; i < n; i++) {
                AWinner.Turn turn = turns.get(i);
                String name = turn.name;
                int score = turn.score + scoreByName.getOrDefault(name, 0);
                scoreByName.put(name, score);
            }
            HashMap<String, Integer> finalScoreByName = scoreByName;
            String winner = null;
            int bestScore = Integer.MIN_VALUE;
            for (int score : scoreByName.values()) {
                if (score > bestScore) {
                    bestScore = score;
                }
            }
            if (bestScore <= 0) throw new AssertionError();
            scoreByName = new HashMap<>();
            for (int i = 0; i < n; i++) {
                AWinner.Turn turn = turns.get(i);
                String name = turn.name;
                int score = turn.score + scoreByName.getOrDefault(name, 0);
                if (finalScoreByName.get(name) == bestScore && score >= bestScore) {
                    winner = name;
                    break;
                }
                scoreByName.put(name, score);
            }
            if (winner == null) throw new AssertionError();
            out.println(winner);
        }

        static class Turn {
            String name;
            int score;
            int id;

            public Turn(String name, int score, int turn) {
                this.name = name;
                this.score = score;
                this.id = turn;
            }

        }

    }

    static class InputReader {
        private InputStream stream;
        private byte[] buf = new byte[65536];
        private int curChar;
        private int numChars;

        public InputReader(InputStream stream) {
            this.stream = stream;
        }

        public int get() {
            if (numChars == -1) {
                throw new RuntimeException();
            }
            if (curChar >= numChars) {
                curChar = 0;
                try {
                    numChars = stream.read(buf);
                } catch (IOException e) {
                    throw new RuntimeException();
                }
                if (numChars <= 0) {
                    return -1;
                }
            }
            return buf[curChar++];
        }

        public String next() {
            int c = get();
            while (isWhitespace(c)) {
                c = get();
            }
            StringBuilder res = new StringBuilder();
            do {
                if (Character.isValidCodePoint(c)) {
                    res.appendCodePoint(c);
                }
                c = get();
            } while (!isWhitespace(c));
            return res.toString();
        }

        public int nextInt() {
            int c = get();
            while (isWhitespace(c)) {
                c = get();
            }
            int sgn = 1;
            if (c == '-') {
                sgn = -1;
                c = get();
            }
            int res = 0;
            do {
                if (c < '0' || c > '9') {
                    throw new RuntimeException();
                }
                res *= 10;
                res += c - '0';
                c = get();
            } while (!isWhitespace(c));
            return res * sgn;
        }

        public static boolean isWhitespace(int c) {
            return c == ' ' || c == '\n' || c == '\r' || c == '\t' || c == -1;
        }

    }
}
