import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.util.Arrays;

/**
 * Code generated by CHelper
 * Original Author: Egor Kulikov
 * Forked and Updated at: https://github.com/nathanwn/idea-chelper
 */
public class Main {
    public static void main(String[] args) {
        InputStream inputStream = System.in;
        OutputStream outputStream = System.out;
        InputReader in = new InputReader(inputStream);
        PrintWriter out = new PrintWriter(outputStream);
        BTPrimes solver = new BTPrimes();
        solver.solve(1, in, out);
        out.close();
    }

    static class BTPrimes {
        final int MAX = (int) 1e6;
        PrimeSieve sieve = new PrimeSieve(MAX);

        public void solve(int testNumber, InputReader in, PrintWriter out) {
            int t = in.nextInt();
            for (int i = 0; i < t; i++) {
                long n = in.nextLong();
                out.println(check(n) ? "YES" : "NO");
            }
        }

        boolean check(long n) {
            int low = 0;
            int high = sieve.primes.size() - 1;
            while (low <= high) {
                int mid = low + (high - low) / 2;
                int p = sieve.primes.get(mid);
                long p2 = (long) p * p;
                if (p2 == n) {
                    return true;
                } else if (p2 < n) {
                    low = mid + 1;
                } else {
                    high = mid - 1;
                }
            }
            return false;
        }

    }

    static class InputReader {
        private InputStream stream;
        private byte[] buf = new byte[65536];
        private int curChar;
        private int numChars;

        public InputReader(InputStream stream) {
            this.stream = stream;
        }

        public int get() {
            if (numChars == -1) {
                throw new RuntimeException();
            }
            if (curChar >= numChars) {
                curChar = 0;
                try {
                    numChars = stream.read(buf);
                } catch (IOException e) {
                    throw new RuntimeException();
                }
                if (numChars <= 0) {
                    return -1;
                }
            }
            return buf[curChar++];
        }

        public int nextInt() {
            int c = get();
            while (isWhitespace(c)) {
                c = get();
            }
            int sgn = 1;
            if (c == '-') {
                sgn = -1;
                c = get();
            }
            int res = 0;
            do {
                if (c < '0' || c > '9') {
                    throw new RuntimeException();
                }
                res *= 10;
                res += c - '0';
                c = get();
            } while (!isWhitespace(c));
            return res * sgn;
        }

        public long nextLong() {
            int c = get();
            while (isWhitespace(c)) {
                c = get();
            }
            int sgn = 1;
            if (c == '-') {
                sgn = -1;
                c = get();
            }
            long res = 0;
            do {
                if (c < '0' || c > '9') {
                    throw new RuntimeException();
                }
                res *= 10;
                res += c - '0';
                c = get();
            } while (!isWhitespace(c));
            return res * sgn;
        }

        public static boolean isWhitespace(int c) {
            return c == ' ' || c == '\n' || c == '\r' || c == '\t' || c == -1;
        }

    }

    static class IntList {
        int cap;
        int n;
        int[] a;

        public IntList() {
            this(16);
        }

        public IntList(int cap) {
            this.cap = cap;
            this.n = 0;
            this.a = new int[cap];
        }

        public int size() {
            return n;
        }

        public int get(int i) {
            return a[i];
        }

        public void add(int x) {
            if (n == cap) {
                cap <<= 1;
                a = Arrays.copyOf(a, cap);
            }
            a[n] = x;
            n++;
        }

    }

    static class PrimeSieve {
        int max;
        public boolean[] isPrime;
        public IntList primes;

        public PrimeSieve(int max) {
            this.max = max;
            this.isPrime = new boolean[max + 1];
            this.primes = new IntList();
            Arrays.fill(isPrime, true);
            for (int i = 2; i * i <= max; i++) {
                if (isPrime[i]) {
                    for (int j = i * i; j <= max; j += i) {
                        isPrime[j] = false;
                    }
                }
            }
            for (int i = 2; i <= max; i++) {
                if (isPrime[i]) {
                    primes.add(i);
                }
            }
        }

    }
}
