import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.TreeSet;

/**
 * Code generated by CHelper
 * Original Author: Egor Kulikov
 * Forked and Updated at: https://github.com/nathanwn/idea-chelper
 */
public class Main {
    public static void main(String[] args) {
        InputStream inputStream = System.in;
        OutputStream outputStream = System.out;
        InputReader in = new InputReader(inputStream);
        PrintWriter out = new PrintWriter(outputStream);
        DPaidWalk solver = new DPaidWalk();
        solver.solve(1, in, out);
        out.close();
    }

    static class DPaidWalk {
        public void solve(int testNumber, InputReader in, PrintWriter out) {
            int n = in.nextInt();
            int m = in.nextInt();
            int l = in.nextInt();
            int minCost = in.nextInt();
            int maxCost = in.nextInt();
            ArrayList<ArrayList<DPaidWalk.Edge>> adj = new ArrayList<>(n);
            for (int u = 0; u < n; u++) {
                adj.add(new ArrayList<>());
            }
            for (int i = 0; i < m; i++) {
                int u = in.nextInt() - 1;
                int v = in.nextInt() - 1;
                int w = in.nextInt();
                adj.get(u).add(new DPaidWalk.Edge(v, w));
            }
            ArrayDeque<DPaidWalk.State> q = new ArrayDeque<>();
            q.addLast(new DPaidWalk.State(0, 0, 0));
            TreeSet<Integer> res = new TreeSet<>();
            while (!q.isEmpty()) {
                DPaidWalk.State cur = q.pollFirst();
                if (cur.d == l) {
                    if (minCost <= cur.c && cur.c <= maxCost) {
                        res.add(cur.u);
                    }
                    continue;
                }
                for (DPaidWalk.Edge e : adj.get(cur.u)) {
                    q.add(new DPaidWalk.State(e.v, cur.d + 1, cur.c + e.w));
                }
            }
            for (Integer u : res) {
                out.print((u + 1) + " ");
            }
            out.println();
        }

        static class Edge {
            int v;
            int w;

            public Edge(int v, int w) {
                this.v = v;
                this.w = w;
            }

        }

        static class State {
            int u;
            int d;
            long c;

            public State(int u, int d, long c) {
                this.u = u;
                this.d = d;
                this.c = c;
            }

            public String toString() {
                return "State{" +
                        "u=" + u +
                        ", d=" + d +
                        ", c=" + c +
                        '}';
            }

        }

    }

    static class InputReader {
        private InputStream stream;
        private byte[] buf = new byte[65536];
        private int curChar;
        private int numChars;

        public InputReader(InputStream stream) {
            this.stream = stream;
        }

        public int get() {
            if (numChars == -1) {
                throw new RuntimeException();
            }
            if (curChar >= numChars) {
                curChar = 0;
                try {
                    numChars = stream.read(buf);
                } catch (IOException e) {
                    throw new RuntimeException();
                }
                if (numChars <= 0) {
                    return -1;
                }
            }
            return buf[curChar++];
        }

        public int nextInt() {
            int c = get();
            while (isWhitespace(c)) {
                c = get();
            }
            int sgn = 1;
            if (c == '-') {
                sgn = -1;
                c = get();
            }
            int res = 0;
            do {
                if (c < '0' || c > '9') {
                    throw new RuntimeException();
                }
                res *= 10;
                res += c - '0';
                c = get();
            } while (!isWhitespace(c));
            return res * sgn;
        }

        public static boolean isWhitespace(int c) {
            return c == ' ' || c == '\n' || c == '\r' || c == '\t' || c == -1;
        }

    }
}

