import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;

/**
 * Code generated by CHelper
 * Original Author: Egor Kulikov
 * Forked and Updated at: https://github.com/nathanwn/idea-chelper
 */
public class Main {
    public static void main(String[] args) {
        InputStream inputStream = System.in;
        OutputStream outputStream = System.out;
        InputReader in = new InputReader(inputStream);
        PrintWriter out = new PrintWriter(outputStream);
        BPassword solver = new BPassword();
        solver.solve(1, in, out);
        out.close();
    }

    static class BPassword {
        public void solve(int testNumber, InputReader in, PrintWriter out) {
            String s = in.next();
            int n = s.length();
            int[] pi = KMP.calcPrefixFunction(s);
            boolean[] hasSubStrWithLen = new boolean[n + 1];
            for (int i = 1; i < n - 1; i++) {
                hasSubStrWithLen[pi[i]] = true;
            }
            for (int len = pi[n - 1]; len > 0; len = pi[len - 1]) {
                if (hasSubStrWithLen[len]) {
                    out.println(s.substring(0, len));
                    return;
                }
            }
            out.println("Just a legend");
        }

    }

    static class InputReader {
        private InputStream stream;
        private byte[] buf = new byte[65536];
        private int curChar;
        private int numChars;

        public InputReader(InputStream stream) {
            this.stream = stream;
        }

        public int get() {
            if (numChars == -1) {
                throw new RuntimeException();
            }
            if (curChar >= numChars) {
                curChar = 0;
                try {
                    numChars = stream.read(buf);
                } catch (IOException e) {
                    throw new RuntimeException();
                }
                if (numChars <= 0) {
                    return -1;
                }
            }
            return buf[curChar++];
        }

        public String next() {
            int c = get();
            while (isWhitespace(c)) {
                c = get();
            }
            StringBuilder res = new StringBuilder();
            do {
                if (Character.isValidCodePoint(c)) {
                    res.appendCodePoint(c);
                }
                c = get();
            } while (!isWhitespace(c));
            return res.toString();
        }

        public static boolean isWhitespace(int c) {
            return c == ' ' || c == '\n' || c == '\r' || c == '\t' || c == -1;
        }

    }

    static class KMP {
        public static int[] calcPrefixFunction(String s) {
            int n = s.length();
            int[] prefix = new int[n];
            for (int i = 1; i < n; i++) {
                int j = prefix[i - 1];
                while (j > 0 && s.charAt(i) != s.charAt(j)) {
                    j = prefix[j - 1];
                }
                if (s.charAt(i) == s.charAt(j)) {
                    j++;
                }
                prefix[i] = j;
            }
            return prefix;
        }

    }
}
