import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;

/**
 * Code generated by CHelper
 * Original Author: Egor Kulikov
 * Forked and Updated at: https://github.com/nathanwn/idea-chelper
 */
public class Main {
    public static void main(String[] args) {
        InputStream inputStream = System.in;
        OutputStream outputStream = System.out;
        InputReader in = new InputReader(inputStream);
        PrintWriter out = new PrintWriter(outputStream);
        DMultipleOf2019 solver = new DMultipleOf2019();
        solver.solve(1, in, out);
        out.close();
    }

    static class DMultipleOf2019 {
        final int MOD = 2019;

        public void solve(int testNumber, InputReader in, PrintWriter out) {
            char[] a = in.next().toCharArray();
            int n = a.length;
            int[] cnt = new int[MOD + 1];
            // If two suffixes a[left:] and a[right+1:] has
            // (sum(a[left:]) - sum(a[right+1:])) mod 2019 == 0
            // then sum(a[left:right]) mod 2019 == 0 because 10 is coprime
            // with 2019, and therefore removing trailing 0s from a number x
            // does not affect x mod 2019.
            // The problem is then about for each suffix a[left:], find
            // how many suffixes a[right+1:] with sum(a[left:]) and sum(a[right+1:])
            // being congruent modulo 2019.
            // If both sums are congruent modulo 2019, the different will be
            // divisible by 2019 and the sum of the subarray a[left:right] will
            // also be divisible by 2019.
            cnt[0] = 1;  // base case of right == n-1
            int powerTen = 1;
            int sum = 0;
            long ans = 0;
            for (int left = n - 1; left >= 0; left--) {
                int digit = a[left] - '0';
                powerTen = modMul(powerTen, 10);
                sum = modAdd(sum, modMul(digit, powerTen));
                ans += cnt[sum];
                cnt[sum]++;
            }
            out.println(ans);
        }

        int modAdd(int a, int b) {
            int c = a + b;
            if (c >= MOD) c -= MOD;
            return c;
        }

        int modMul(int a, int b) {
            return (int) ((long) a * b % MOD);
        }

    }

    static class InputReader {
        private InputStream stream;
        private byte[] buf = new byte[65536];
        private int curChar;
        private int numChars;

        public InputReader(InputStream stream) {
            this.stream = stream;
        }

        public int get() {
            if (numChars == -1) {
                throw new RuntimeException();
            }
            if (curChar >= numChars) {
                curChar = 0;
                try {
                    numChars = stream.read(buf);
                } catch (IOException e) {
                    throw new RuntimeException();
                }
                if (numChars <= 0) {
                    return -1;
                }
            }
            return buf[curChar++];
        }

        public String next() {
            int c = get();
            while (isWhitespace(c)) {
                c = get();
            }
            StringBuilder res = new StringBuilder();
            do {
                if (Character.isValidCodePoint(c)) {
                    res.appendCodePoint(c);
                }
                c = get();
            } while (!isWhitespace(c));
            return res.toString();
        }

        public static boolean isWhitespace(int c) {
            return c == ' ' || c == '\n' || c == '\r' || c == '\t' || c == -1;
        }

    }
}

