import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;

/**
 * Code generated by CHelper
 * Original Author: Egor Kulikov
 * Forked and Updated at: https://github.com/nathanwn/idea-chelper
 */
public class Main {
    public static void main(String[] args) {
        InputStream inputStream = System.in;
        OutputStream outputStream = System.out;
        InputReader in = new InputReader(inputStream);
        PrintWriter out = new PrintWriter(outputStream);
        BTwoLanguages solver = new BTwoLanguages();
        solver.solve(1, in, out);
        out.close();
    }

    static class BTwoLanguages {
        public void solve(int testNumber, InputReader in, PrintWriter out) {
            int n = in.nextInt();
            int m = in.nextInt();
            char[] s = in.next().toCharArray();
            char[] t = in.next().toCharArray();
            int q = in.nextInt();
            char[][] w = new char[q][];
            for (int j = 0; j < q; j++) {
                w[j] = in.next().toCharArray();
            }
            int[] sf = toFreq(s);
            int[] tf = toFreq(t);
            for (int j = 0; j < q; j++) {
                boolean a = isIn(w[j], sf);
                boolean b = isIn(w[j], tf);
                if (a && b) {
                    out.println("Unknown");
                    continue;
                }
                if (a) {
                    out.println("Takahashi");
                    continue;
                }
                if (b) {
                    out.println("Aoki");
                    continue;
                }
                out.println("Unknown");
            }
        }

        private boolean isIn(char[] chars, int[] f) {
            for (char c : chars) {
                if (f[c - 'a'] == 0) {
                    return false;
                }
            }
            return true;
        }

        int[] toFreq(char[] s) {
            int[] f = new int[26];
            for (char c : s) {
                f[c - 'a']++;
            }
            return f;
        }

    }

    static class InputReader {
        private InputStream stream;
        private byte[] buf = new byte[65536];
        private int curChar;
        private int numChars;

        public InputReader(InputStream stream) {
            this.stream = stream;
        }

        public int get() {
            if (numChars == -1) {
                throw new RuntimeException();
            }
            if (curChar >= numChars) {
                curChar = 0;
                try {
                    numChars = stream.read(buf);
                } catch (IOException e) {
                    throw new RuntimeException();
                }
                if (numChars <= 0) {
                    return -1;
                }
            }
            return buf[curChar++];
        }

        public String next() {
            int c = get();
            while (isWhitespace(c)) {
                c = get();
            }
            StringBuilder res = new StringBuilder();
            do {
                if (Character.isValidCodePoint(c)) {
                    res.appendCodePoint(c);
                }
                c = get();
            } while (!isWhitespace(c));
            return res.toString();
        }

        public int nextInt() {
            int c = get();
            while (isWhitespace(c)) {
                c = get();
            }
            int sgn = 1;
            if (c == '-') {
                sgn = -1;
                c = get();
            }
            int res = 0;
            do {
                if (c < '0' || c > '9') {
                    throw new RuntimeException();
                }
                res *= 10;
                res += c - '0';
                c = get();
            } while (!isWhitespace(c));
            return res * sgn;
        }

        public static boolean isWhitespace(int c) {
            return c == ' ' || c == '\n' || c == '\r' || c == '\t' || c == -1;
        }

    }
}
