import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;

/**
 * Code generated by CHelper
 * Original Author: Egor Kulikov
 * Forked and Updated at: https://github.com/nathanwn/idea-chelper
 */
public class Main {
    public static void main(String[] args) {
        InputStream inputStream = System.in;
        OutputStream outputStream = System.out;
        InputReader in = new InputReader(inputStream);
        PrintWriter out = new PrintWriter(outputStream);
        BImpostOrSus solver = new BImpostOrSus();
        solver.solve(1, in, out);
        out.close();
    }

    static class BImpostOrSus {
        public void solve(int testNumber, InputReader in, PrintWriter out) {
            int t = in.nextInt();
            while (t-- > 0) {
                solveCase(in, out);
            }
        }

        private void solveCase(InputReader in, PrintWriter out) {
            String ss = in.next();
            int resGreedy = solveGreedy(ss);
            int resDP = solveDP(ss);
            if (resGreedy != resDP) throw new AssertionError();
            out.println(resGreedy);
        }

        private int solveGreedy(String ss) {
            char[] s = ss.toCharArray();
            int n = s.length;
            int res = 0;
            if (s[0] == 'u') {
                s[0] = 's';
                res++;
            }
            if (s[n - 1] == 'u') {
                s[n - 1] = 's';
                res++;
            }
            // For each consecutive block of 'u' chars, keep the odd positions.
            for (int i = 2; i < n - 1; i++) {
                if (s[i - 1] == 'u' && s[i] == 'u') {
                    s[i] = 's';
                    res++;
                }
            }
            return res;
        }

        private int solveDP(String ss) {
            char[] s = ss.toCharArray();
            int n = s.length;
            final int INF = (int) 1e9;
            int[] dpU = new int[n];
            int[] dpS = new int[n];
            if (s[0] == 'u') {
                dpS[0] = 1;
            } else {
                dpS[0] = 0;
            }
            dpU[0] = INF;
            for (int i = 1; i < n; i++) {
                if (s[i] == 'u') {
                    dpU[i] = dpS[i - 1];
                } else {
                    dpU[i] = INF;
                }
                dpS[i] = (s[i] == 'u' ? 1 : 0) + Math.min(dpU[i - 1], dpS[i - 1]);
            }
            return dpS[n - 1];
        }

    }

    static class InputReader {
        private InputStream stream;
        private byte[] buf = new byte[65536];
        private int curChar;
        private int numChars;

        public InputReader(InputStream stream) {
            this.stream = stream;
        }

        public int get() {
            if (numChars == -1) {
                throw new RuntimeException();
            }
            if (curChar >= numChars) {
                curChar = 0;
                try {
                    numChars = stream.read(buf);
                } catch (IOException e) {
                    throw new RuntimeException();
                }
                if (numChars <= 0) {
                    return -1;
                }
            }
            return buf[curChar++];
        }

        public String next() {
            int c = get();
            while (isWhitespace(c)) {
                c = get();
            }
            StringBuilder res = new StringBuilder();
            do {
                if (Character.isValidCodePoint(c)) {
                    res.appendCodePoint(c);
                }
                c = get();
            } while (!isWhitespace(c));
            return res.toString();
        }

        public int nextInt() {
            int c = get();
            while (isWhitespace(c)) {
                c = get();
            }
            int sgn = 1;
            if (c == '-') {
                sgn = -1;
                c = get();
            }
            int res = 0;
            do {
                if (c < '0' || c > '9') {
                    throw new RuntimeException();
                }
                res *= 10;
                res += c - '0';
                c = get();
            } while (!isWhitespace(c));
            return res * sgn;
        }

        public static boolean isWhitespace(int c) {
            return c == ' ' || c == '\n' || c == '\r' || c == '\t' || c == -1;
        }

    }
}
